{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rfidreaderconnect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/rfidreaderconnect"]}],"metadata":{"externalID":"RFIDReaderConnect","role":"collection","title":"RFIDReaderConnect","symbolKind":"module","modules":[{"name":"RFIDReaderConnect"}],"roleHeading":"Framework"},"primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"Overview","text":"Overview","level":2}]}],"hierarchy":{"paths":[[]]},"kind":"symbol","topicSections":[{"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReader","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderAntennaPort","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderSerialNumber","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderTagSingulationData","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderVersion","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDTag","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDTagPhase"],"generated":true},{"identifiers":["doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderDelegate"],"anchor":"Protocols","title":"Protocols","generated":true},{"generated":true,"title":"Type Aliases","anchor":"Type-Aliases","identifiers":["doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDTagMemoryAddress","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDTagPassword"]},{"title":"Enumerations","anchor":"Enumerations","identifiers":["doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderBaudRate","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderCommMode","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderConfiguration","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderError","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderModel","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderNotificationType","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderQ","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderRFMode","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderRegion","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderSession","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderTagMetadata","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderTagSingulationFlag","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderTarget","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDTagMemoryBank","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/TransportType","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/WiFiTransportMode"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderQ":{"type":"topic","url":"\/documentation\/rfidreaderconnect\/rfidreaderq","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderQ","title":"RFIDReaderQ","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RFIDReaderQ","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RFIDReaderQ"}],"abstract":[]},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderTarget":{"identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderTarget","title":"RFIDReaderTarget","type":"topic","role":"symbol","url":"\/documentation\/rfidreaderconnect\/rfidreadertarget","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RFIDReaderTarget","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RFIDReaderTarget"}]},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderRegion":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RFIDReaderRegion","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"RFIDReaderRegion","kind":"identifier"}],"identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderRegion","title":"RFIDReaderRegion","url":"\/documentation\/rfidreaderconnect\/rfidreaderregion","role":"symbol"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDTagPassword":{"navigatorTitle":[{"text":"RFIDTagPassword","kind":"identifier"}],"url":"\/documentation\/rfidreaderconnect\/rfidtagpassword","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"RFIDTagPassword","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"4 bytes password"}],"title":"RFIDTagPassword","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDTagPassword"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/TransportType":{"navigatorTitle":[{"text":"TransportType","kind":"identifier"}],"url":"\/documentation\/rfidreaderconnect\/transporttype","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TransportType","kind":"identifier"}],"title":"TransportType","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/TransportType","kind":"symbol"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderTagMetadata":{"title":"RFIDReaderTagMetadata","url":"\/documentation\/rfidreaderconnect\/rfidreadertagmetadata","navigatorTitle":[{"kind":"identifier","text":"RFIDReaderTagMetadata"}],"identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderTagMetadata","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RFIDReaderTagMetadata","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderTagSingulationFlag":{"abstract":[],"title":"RFIDReaderTagSingulationFlag","navigatorTitle":[{"text":"RFIDReaderTagSingulationFlag","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderTagSingulationFlag","role":"symbol","url":"\/documentation\/rfidreaderconnect\/rfidreadertagsingulationflag","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RFIDReaderTagSingulationFlag","kind":"identifier"}]},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderTagSingulationData":{"url":"\/documentation\/rfidreaderconnect\/rfidreadertagsingulationdata","navigatorTitle":[{"text":"RFIDReaderTagSingulationData","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderTagSingulationData","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RFIDReaderTagSingulationData","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"RFIDReaderTagSingulationData"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderAntennaPort":{"url":"\/documentation\/rfidreaderconnect\/rfidreaderantennaport","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RFIDReaderAntennaPort"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderAntennaPort","navigatorTitle":[{"kind":"identifier","text":"RFIDReaderAntennaPort"}],"type":"topic","title":"RFIDReaderAntennaPort"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderRFMode":{"navigatorTitle":[{"text":"RFIDReaderRFMode","kind":"identifier"}],"abstract":[],"title":"RFIDReaderRFMode","url":"\/documentation\/rfidreaderconnect\/rfidreaderrfmode","type":"topic","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderRFMode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RFIDReaderRFMode","kind":"identifier"}],"role":"symbol"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderSerialNumber":{"identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderSerialNumber","url":"\/documentation\/rfidreaderconnect\/rfidreaderserialnumber","navigatorTitle":[{"kind":"identifier","text":"RFIDReaderSerialNumber"}],"title":"RFIDReaderSerialNumber","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RFIDReaderSerialNumber"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderCommMode":{"type":"topic","title":"RFIDReaderCommMode","role":"symbol","url":"\/documentation\/rfidreaderconnect\/rfidreadercommmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"RFIDReaderCommMode","kind":"identifier"}],"navigatorTitle":[{"text":"RFIDReaderCommMode","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderCommMode","kind":"symbol"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderModel":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RFIDReaderModel"}],"identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderModel","abstract":[],"navigatorTitle":[{"text":"RFIDReaderModel","kind":"identifier"}],"title":"RFIDReaderModel","type":"topic","url":"\/documentation\/rfidreaderconnect\/rfidreadermodel"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderError":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RFIDReaderError"}],"role":"symbol","navigatorTitle":[{"text":"RFIDReaderError","kind":"identifier"}],"title":"RFIDReaderError","url":"\/documentation\/rfidreaderconnect\/rfidreadererror","type":"topic","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderError","abstract":[]},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderConnectVersionNumber":{"type":"topic","url":"\/documentation\/rfidreaderconnect\/rfidreaderconnectversionnumber","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderConnectVersionNumber","title":"RFIDReaderConnectVersionNumber","role":"symbol","fragments":[{"text":"RFIDReaderConnectVersionNumber","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Project version number for RFIDReaderConnect."}]},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderBaudRate":{"navigatorTitle":[{"kind":"identifier","text":"RFIDReaderBaudRate"}],"identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderBaudRate","title":"RFIDReaderBaudRate","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RFIDReaderBaudRate","kind":"identifier"}],"url":"\/documentation\/rfidreaderconnect\/rfidreaderbaudrate","type":"topic","abstract":[],"kind":"symbol"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderVersion":{"role":"symbol","url":"\/documentation\/rfidreaderconnect\/rfidreaderversion","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RFIDReaderVersion"}],"title":"RFIDReaderVersion","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderVersion","type":"topic","abstract":[],"navigatorTitle":[{"text":"RFIDReaderVersion","kind":"identifier"}],"kind":"symbol"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect":{"type":"topic","abstract":[],"url":"\/documentation\/rfidreaderconnect","role":"collection","title":"RFIDReaderConnect","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect","kind":"symbol"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderConnectVersionString":{"type":"topic","role":"symbol","fragments":[{"text":"RFIDReaderConnectVersionString","kind":"identifier"}],"identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderConnectVersionString","kind":"symbol","abstract":[{"text":"Project version string for RFIDReaderConnect.","type":"text"}],"url":"\/documentation\/rfidreaderconnect\/rfidreaderconnectversionstring","title":"RFIDReaderConnectVersionString"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDTagMemoryBank":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RFIDTagMemoryBank","kind":"identifier"}],"identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDTagMemoryBank","type":"topic","title":"RFIDTagMemoryBank","url":"\/documentation\/rfidreaderconnect\/rfidtagmemorybank","navigatorTitle":[{"kind":"identifier","text":"RFIDTagMemoryBank"}],"kind":"symbol","role":"symbol","abstract":[]},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDTagMemoryAddress":{"identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDTagMemoryAddress","navigatorTitle":[{"kind":"identifier","text":"RFIDTagMemoryAddress"}],"url":"\/documentation\/rfidreaderconnect\/rfidtagmemoryaddress","kind":"symbol","role":"symbol","type":"topic","title":"RFIDTagMemoryAddress","abstract":[{"text":"4 bytes memory address","type":"text"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"RFIDTagMemoryAddress","kind":"identifier"}]},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderSession":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RFIDReaderSession"}],"navigatorTitle":[{"kind":"identifier","text":"RFIDReaderSession"}],"title":"RFIDReaderSession","kind":"symbol","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderSession","abstract":[],"url":"\/documentation\/rfidreaderconnect\/rfidreadersession"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDTagPhase":{"role":"symbol","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDTagPhase","title":"RFIDTagPhase","url":"\/documentation\/rfidreaderconnect\/rfidtagphase","type":"topic","kind":"symbol","navigatorTitle":[{"text":"RFIDTagPhase","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RFIDTagPhase","kind":"identifier"}]},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReader":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/rfidreaderconnect\/rfidreader","title":"RFIDReader","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RFIDReader"}],"navigatorTitle":[{"text":"RFIDReader","kind":"identifier"}],"type":"topic"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderConfiguration":{"title":"RFIDReaderConfiguration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"RFIDReaderConfiguration","kind":"identifier"}],"url":"\/documentation\/rfidreaderconnect\/rfidreaderconfiguration","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderConfiguration","abstract":[],"type":"topic","navigatorTitle":[{"text":"RFIDReaderConfiguration","kind":"identifier"}]},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDTag":{"navigatorTitle":[{"text":"RFIDTag","kind":"identifier"}],"title":"RFIDTag","kind":"symbol","url":"\/documentation\/rfidreaderconnect\/rfidtag","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RFIDTag","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDTag","type":"topic","abstract":[]},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderNotificationType":{"title":"RFIDReaderNotificationType","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RFIDReaderNotificationType","kind":"identifier"}],"url":"\/documentation\/rfidreaderconnect\/rfidreadernotificationtype","abstract":[],"identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderNotificationType","role":"symbol","navigatorTitle":[{"text":"RFIDReaderNotificationType","kind":"identifier"}],"kind":"symbol"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/RFIDReaderDelegate":{"navigatorTitle":[{"text":"RFIDReaderDelegate","kind":"identifier"}],"url":"\/documentation\/rfidreaderconnect\/rfidreaderdelegate","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"RFIDReaderDelegate","kind":"identifier"}],"title":"RFIDReaderDelegate","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderDelegate","kind":"symbol"},"doc://com.bypratham.RFIDReaderConnect/documentation/RFIDReaderConnect/WiFiTransportMode":{"navigatorTitle":[{"kind":"identifier","text":"WiFiTransportMode"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WiFiTransportMode"}],"url":"\/documentation\/rfidreaderconnect\/wifitransportmode","identifier":"doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/WiFiTransportMode","abstract":[],"title":"WiFiTransportMode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderConnectVersionNumber","doc:\/\/com.bypratham.RFIDReaderConnect\/documentation\/RFIDReaderConnect\/RFIDReaderConnectVersionString"],"anchor":"Variables","title":"Variables"}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"}]}]}